name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/node@8daf3354cad97676fd0bb06cc12f2498441130c1 # v1.200.0
        with:
          audit: true

      - run: npm run prettier -- --check
      - run: npx nx run-many -t lint
      - run: npx nx run-many -t build
      - run: npx nx run-many -t test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
