name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/node@v1.102.0

      - run: npx nx run-many -t lint
      - run: npx nx run-many -t build
      - run: npx nx run-many -t test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
